/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Menu.componentes.Info_Mazo;
import Menu.componentes.casillas;
import java.awt.Graphics;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.ImageIcon;

/**
 *
 * @author Andro
 */
public class Menu_CrearMazo extends javax.swing.JFrame {

    private String lmazo;
    private int idTarjeta;
    private ImageIcon sprite;
    private Info_Mazo info_mazo;
    
    
    int numero = 0;
    
    

    /**
     * Creates new form Menu_CrearMazo
     */
    public Menu_CrearMazo() {
        initComponents();
        
        añadirmazo();
      
       
        
    }
    
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
       int i,j =0;
        while(idTarjeta<20){
            
            for(i=100;i<=200;i=i+100){
                for(j=0;j<800;j=j+80){
       
                    idTarjeta++;
                    this.sprite = new ImageIcon(getClass().getResource("/imagenes/JPD_PA"+idTarjeta+".png"));
                    g.drawImage(sprite.getImage(), 30+j,0+i, 70, 90, this);
        
                }
            }
        }
    }
    
    
    /*deteccion de carta*/

    
    
    
    
     public void añadirmazo(){
        Info_Mazo m = new Info_Mazo();
        m.setVisible(true);
        mazo.add(m);
       
           
     }
     
     
     public void añadirCasillas(){
         for(int i=1;i<20;i++){
        casillas c = new casillas(i);
        c.setVisible(true);
        c.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    // Tu lógica al hacer clic en la casilla
                    añadirmazo();
                  info_mazo.mostrarInfoEnNuevoFrame(c.getIdTarjeta());
                    c.actualizarSprite(0);
                    agregarLetra( c.getIdTarjeta());
                    // Puedes agregar cualquier acción que desees realizar aquí
                    contador.setText(Integer.toString(numero));
                }
            });
        this.add(c);
        this.repaint();
         }
    }
     
  public void agregarLetra(int id) {
       
    
            char letra = (char) ('A' + id - 1);
            lmazo=lmazo+letra;
       
           
        }
  
  private void sumarUno() {
        
        numero++;
        contador.setText(Integer.toString(numero));
    
  }
     
     
     
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lista = new javax.swing.JPanel();
        mazo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout listaLayout = new javax.swing.GroupLayout(lista);
        lista.setLayout(listaLayout);
        listaLayout.setHorizontalGroup(
            listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        listaLayout.setVerticalGroup(
            listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 270));

        mazo.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout mazoLayout = new javax.swing.GroupLayout(mazo);
        mazo.setLayout(mazoLayout);
        mazoLayout.setHorizontalGroup(
            mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        mazoLayout.setVerticalGroup(
            mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(mazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 340, 210));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 90, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("tamaño de mazo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 170, 50));

        contador.setBackground(new java.awt.Color(255, 255, 255));
        contador.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        contador.setForeground(new java.awt.Color(255, 255, 255));
        contador.setText("0");
        getContentPane().add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 20, 30));

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  //* guardar la variable lmazo en base de datos*//
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_CrearMazo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_CrearMazo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_CrearMazo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_CrearMazo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_CrearMazo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel lista;
    private javax.swing.JPanel mazo;
    // End of variables declaration//GEN-END:variables
}
