/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Campo;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Marti
 */
public class Mano extends javax.swing.JPanel implements MouseListener {
    
    private int cartaSeleccionada;
    private int tamanoMano;

    /**
     * Creates new form Mano
     */
    public Mano() {
        initComponents();
    }
    
    public void anadirTarjeta(int i){
        Casilla c = new Casilla(i);
        c.setNumeroCarta(tamanoMano +1);
        this.tamanoMano += 1;
        c.setVisible(true);
        c.addMouseListener(this);
        this.add(c);
        this.updateUI();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 255));
        setMaximumSize(new java.awt.Dimension(1000, 200));
        setMinimumSize(new java.awt.Dimension(1000, 200));
        setPreferredSize(new java.awt.Dimension(1000, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void mouseClicked(MouseEvent e) {
        if (cartaSeleccionada == 0){
            if (e.getSource().getClass() == Casilla.class) {
                if (((Casilla) e.getSource()).getTipoCasilla() == 1){
                    this.cartaSeleccionada = ((Casilla) e.getSource()).getNumeroCarta();
                }
            }
        }
    }

    public int getCartaSeleccionada() {
        return cartaSeleccionada;
    }

    @Override
    public void mousePressed(MouseEvent e) {
        return;
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        return;
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        return;
    }

    @Override
    public void mouseExited(MouseEvent e) {
        return;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
