/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Campo;

/**
 *
 * @author Marti
 * 
 * La Mano muestra por la GUI las cartas que tiene disponible el jugador para
 * jugar en su turno
 */
public class Mano extends javax.swing.JPanel{

    /**
     * Creates new form Mano
     */
    public Mano() {
        initComponents();
    }
    
    /* Añade un nuevo sprite de carta a la Mano a partir del Id de la carta*/
    public void anadirTarjeta(int i){
        Casilla c = new Casilla(i);
        c.setVisible(true);
        c.addMouseListener(this.getMouseListeners()[0]);
        this.add(c);
        this.updateUI();
    } 
    
    /* Elimina el sprite de una carta que sale de la Mano*/
    public void eliminarCarta(int i) {
        this.remove(i);
        this.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 255));
        setMaximumSize(new java.awt.Dimension(1000, 200));
        setMinimumSize(new java.awt.Dimension(1000, 200));
        setPreferredSize(new java.awt.Dimension(1000, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
