/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package  GUI;
import javax.swing.*;
/**
 *
 * @author Andro
 */
public class VistaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public VistaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txtfield_nombre = new javax.swing.JTextField();
        Jfield_contrasena = new javax.swing.JPasswordField();
        Jfield_contrasenaconfirm = new javax.swing.JPasswordField();
        bt_registrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Jlabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 375));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese sus datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        Txtfield_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtfield_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(Txtfield_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 240, -1));

        Jfield_contrasena.setText("jPasswordField1");
        getContentPane().add(Jfield_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 240, -1));

        Jfield_contrasenaconfirm.setText("jPasswordField2");
        getContentPane().add(Jfield_contrasenaconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, -1));

        bt_registrar.setText("Enviar");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirme contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        Jlabel_fondo.setBackground(new java.awt.Color(51, 0, 102));
        Jlabel_fondo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Jlabel_fondo.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel_fondo.setOpaque(true);
        getContentPane().add(Jlabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txtfield_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtfield_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtfield_nombreActionPerformed

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
    
           if(Txtfield_nombre.getText().length()<0 || Jfield_contrasenaconfirm.getText().length()<0 || Jfield_contrasenaconfirm.getText().length()<0 ){
               JOptionPane.showMessageDialog(null, "campos vacios");
           }
        
    }//GEN-LAST:event_bt_registrarActionPerformed

     private void Txtfield_nombreKeyTyped(java.awt.event.KeyEvent evt) {                                         
        
    if(Txtfield_nombre.getText().length() >= 30){
         JOptionPane.showMessageDialog(null, " el nombre solo puede tener 30 caracteres");
        evt.consume();
    }

    }                                                                                        

    private void Jfield_contrasenaKeyTyped(java.awt.event.KeyEvent evt) {                                           
      if(Jfield_contrasena.getText().length() >= 8){
           JOptionPane.showMessageDialog(null, " la contraseña solo pueded tener 8 caracteres");
        evt.consume();
    }
    }                                          

    private void Jfield_contrasenaconfirmKeyTyped(java.awt.event.KeyEvent evt) {                                                  
       if(Jfield_contrasenaconfirm.getText().length() >= 8){
           JOptionPane.showMessageDialog(null, " la contraseña solo pueded tener 8 caracteres");
        evt.consume();
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPasswordField Jfield_contrasena;
    public javax.swing.JPasswordField Jfield_contrasenaconfirm;
    private javax.swing.JLabel Jlabel_fondo;
    public javax.swing.JTextField Txtfield_nombre;
    public javax.swing.JButton bt_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
