/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menu.componentes;


import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;
/**
 *
 * @author Andro
 */
public class casillas extends javax.swing.JPanel {

    /**
     * Creates new form casillas
     */
    public casillas() {
        initComponents();
    }
    
     private int tipoCasilla; // 0 para casilla de Campo, 1 para casilla de Mano
    
    private int idTarjeta;
    private ImageIcon sprite;

    /**
     * Casilla dentro de los Campos
     * public casillas() {
        initComponents();
        this.tipoCasilla = 0;
    }
     */
    
    
    /*
        Casilla dentro de la Mano
    */
    public casillas(int i) {
        this.tipoCasilla = 1;
        this.idTarjeta = i;
        initComponents();
        actualizarSprite(idTarjeta);
    }
    
    
    
    /* Actualiza el sprite de cada casilla dependiendo de si tiene carta o no*/
    @Override
    public void paint(Graphics g){
        super.paint(g);
        
        if (idTarjeta == 0){
            g.setColor(Color.CYAN);
            g.fillRect(0, 0, 100, 156);
        }else{
            g.drawImage(sprite.getImage(), 0,0, 100, 156, this);
        }
    }
    
    /* Ubica cual es el sprite al quue se debe actualizar la casilla*/
    public void actualizarSprite(int id){
        this.idTarjeta = id;
        this.sprite = new ImageIcon(getClass().getResource("/imagenes/JPD_PA"+idTarjeta+".png"));
        this.updateUI();
    }
    
    /* Obtiene el tipo de casilla*/
    public int getTipoCasilla() {
        return tipoCasilla;
    }

    public int getIdTarjeta() {
        return idTarjeta;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
