/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menu.componentes;

import java.awt.GridLayout;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Andro
 */
public class Info_Mazo extends javax.swing.JPanel {
    
    private int tamanio_mazo;
    private String mazo;

    /**
     * Creates new form Mazo
     */
    public Info_Mazo() {
        initComponents();
    }
    
    public int getTamanio_mazo() {
        return tamanio_mazo;
    }

    public void setTamanio_mazo(int tamanio_mazo) {
        this.tamanio_mazo = tamanio_mazo;
    }

    public String getMazo() {
        return mazo;
    }

    public void setMazo(String mazo) {
        this.mazo = mazo;
    }
    
    
    
    
    
    public void mostrarInfoEnNuevoFrame(int id) {
        
        Properties propiedades = cargarDatosDesdeProperties();
        
        /* Obtener datos asociados al ID*/
        String nombre = propiedades.getProperty("tarjeta." + id + ".nombre", "Nombre no encontrado");
        int valorAtaque = Integer.parseInt(propiedades.getProperty("tarjeta." + id + ".valorAtaque", "0"));
        int valorDefensa = Integer.parseInt(propiedades.getProperty("tarjeta." + id + ".valorDefensa", "0"));
        int valorMagia = Integer.parseInt(propiedades.getProperty("tarjeta." + id + ".valorMagia", "0"));
        int valorSalud = Integer.parseInt(propiedades.getProperty("tarjeta." + id + ".valorSalud", "0"));

        JFrame infoFrame = new JFrame("Información de Tarjeta");
        JLabel labelTitulo = new JLabel("Información de la Tarjeta " + id);
        JLabel labelNombre = new JLabel("Nombre: " + nombre);
        JLabel labelAtaque = new JLabel("Valor de Ataque: " + valorAtaque);
        JLabel labelDefensa = new JLabel("Valor de Defensa: " + valorDefensa);
        JLabel labelMagia = new JLabel("Valor de Magia: " + valorMagia);
        JLabel labelSalud = new JLabel("Valor de Salud: " + valorSalud);
        
        JPanel panelInfo = new JPanel();
        panelInfo.setLayout(new GridLayout(6, 1));
        panelInfo.add(labelTitulo);
        panelInfo.add(labelNombre);
        panelInfo.add(labelAtaque);
        panelInfo.add(labelDefensa);
        panelInfo.add(labelMagia);
        panelInfo.add(labelSalud);
        
        infoFrame.getContentPane().add(panelInfo);
        
        
        
        
        infoFrame.setSize(300, 200);
        infoFrame.setLocationRelativeTo(null);
        infoFrame.setVisible(true);
        
        
    }

    private Properties cargarDatosDesdeProperties() {
        Properties propiedades = new Properties();
        try (FileInputStream entrada = new FileInputStream("./src/Recursos/Tarjetas.properties")) {
            propiedades.load(entrada);
        } catch (IOException ex) {
            ex.printStackTrace();
            // Manejar la excepción apropiadamente, por ejemplo, mostrar un mensaje de error
        }
        return propiedades;
    }
     
     public static String agregarLetra(int id) {
       
            // Asegurarse de que el número esté en el rango del alfabeto
            char letra = (char) ('A' + id - 1);
            return String.valueOf(letra);
       
           
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
